apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "htar-gateway.fullname" . }}
  labels:
    {{- include "htar-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "htar-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "htar-gateway.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "htar-gateway.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /_htar/health
              port: {{ .Values.config.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /_htar/health
              port: {{ .Values.config.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "htar-gateway.fullname" . }}-config
